ALTER TABLE ai_providers ADD COLUMN proxyEnabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_providers ADD COLUMN proxyType TEXT NOT NULL DEFAULT 'HTTP';
ALTER TABLE ai_providers ADD COLUMN proxyHost TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_providers ADD COLUMN proxyPort INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_providers ADD COLUMN proxyUsername TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_providers ADD COLUMN proxyPassword TEXT NOT NULL DEFAULT '';
